// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine

#include "../ui.h"

lv_obj_t *ui_scrEnvironment = NULL;lv_obj_t *ui_envName = NULL;lv_obj_t *ui_envHeroValue = NULL;lv_obj_t *ui_envHerounit = NULL;lv_obj_t *ui_div4 = NULL;lv_obj_t *ui_envSensor = NULL;lv_obj_t *ui_envSensorV = NULL;lv_obj_t *ui_envChannel = NULL;lv_obj_t *ui_envChannelV = NULL;lv_obj_t *ui_envVoltage = NULL;lv_obj_t *ui_envVoltageV = NULL;lv_obj_t *ui_envStatus = NULL;lv_obj_t *ui_envStatusV = NULL;lv_obj_t *ui_envNav = NULL;lv_obj_t *ui_envNavLegend = NULL;lv_obj_t *ui_envNavGrid = NULL;lv_obj_t *ui_envNavTilt = NULL;lv_obj_t *ui_envNavEnv = NULL;lv_obj_t *ui_envNavCan = NULL;lv_obj_t *ui_envNavPower = NULL;
// event funtions

// build funtions

void ui_scrEnvironment_screen_init(void)
{
ui_scrEnvironment = lv_obj_create(NULL);
lv_obj_remove_flag( ui_scrEnvironment, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_envName = lv_label_create(ui_scrEnvironment);
lv_obj_set_width( ui_envName, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_envName, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_envName, 16 );
lv_obj_set_y( ui_envName, 16 );
lv_label_set_text(ui_envName,"ENVIRONMENT");
ui_object_set_themeable_style_property(ui_envName, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx1);
ui_object_set_themeable_style_property(ui_envName, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx1);
lv_obj_set_style_text_font(ui_envName, &ui_font_InterMedium11, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_envHeroValue = lv_label_create(ui_scrEnvironment);
lv_obj_set_width( ui_envHeroValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_envHeroValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_envHeroValue, 16 );
lv_obj_set_y( ui_envHeroValue, 32 );
lv_label_set_text(ui_envHeroValue,"888");
ui_object_set_themeable_style_property(ui_envHeroValue, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx1);
ui_object_set_themeable_style_property(ui_envHeroValue, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx1);
lv_obj_set_style_text_font(ui_envHeroValue, &ui_font_InterBold28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_envHerounit = lv_label_create(ui_scrEnvironment);
lv_obj_set_width( ui_envHerounit, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_envHerounit, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_envHerounit, 75 );
lv_obj_set_y( ui_envHerounit, 43 );
lv_label_set_text(ui_envHerounit,"ppm - good");
ui_object_set_themeable_style_property(ui_envHerounit, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_okg);
ui_object_set_themeable_style_property(ui_envHerounit, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_okg);
lv_obj_set_style_text_font(ui_envHerounit, &ui_font_InterRegular13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_div4 = lv_obj_create(ui_scrEnvironment);
lv_obj_remove_style_all(ui_div4);
lv_obj_set_width( ui_div4, 288);
lv_obj_set_height( ui_div4, 1);
lv_obj_set_x( ui_div4, 16 );
lv_obj_set_y( ui_div4, 76 );
lv_obj_remove_flag( ui_div4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_div4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_ln0);
ui_object_set_themeable_style_property(ui_div4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_ln0);
lv_obj_set_style_border_width(ui_div4, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_envSensor = lv_label_create(ui_scrEnvironment);
lv_obj_set_width( ui_envSensor, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_envSensor, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_envSensor, 16 );
lv_obj_set_y( ui_envSensor, 88 );
lv_label_set_text(ui_envSensor,"Sensor");
ui_object_set_themeable_style_property(ui_envSensor, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx2);
ui_object_set_themeable_style_property(ui_envSensor, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx2);
lv_obj_set_style_text_font(ui_envSensor, &ui_font_InterRegular13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_envSensorV = lv_label_create(ui_scrEnvironment);
lv_obj_set_width( ui_envSensorV, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_envSensorV, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_envSensorV, -16 );
lv_obj_set_y( ui_envSensorV, 88 );
lv_obj_set_align( ui_envSensorV, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_envSensorV,"MQ-02");
ui_object_set_themeable_style_property(ui_envSensorV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx1);
ui_object_set_themeable_style_property(ui_envSensorV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx1);
lv_obj_set_style_text_font(ui_envSensorV, &ui_font_JetBrainsMedium14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_envChannel = lv_label_create(ui_scrEnvironment);
lv_obj_set_width( ui_envChannel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_envChannel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_envChannel, 16 );
lv_obj_set_y( ui_envChannel, 112 );
lv_label_set_text(ui_envChannel,"ADC Channel");
ui_object_set_themeable_style_property(ui_envChannel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx2);
ui_object_set_themeable_style_property(ui_envChannel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx2);
lv_obj_set_style_text_font(ui_envChannel, &ui_font_InterRegular13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_envChannelV = lv_label_create(ui_scrEnvironment);
lv_obj_set_width( ui_envChannelV, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_envChannelV, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_envChannelV, -16 );
lv_obj_set_y( ui_envChannelV, 112 );
lv_obj_set_align( ui_envChannelV, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_envChannelV,"ADC0_CH3");
ui_object_set_themeable_style_property(ui_envChannelV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx1);
ui_object_set_themeable_style_property(ui_envChannelV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx1);
lv_obj_set_style_text_font(ui_envChannelV, &ui_font_JetBrainsMedium14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_envVoltage = lv_label_create(ui_scrEnvironment);
lv_obj_set_width( ui_envVoltage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_envVoltage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_envVoltage, 16 );
lv_obj_set_y( ui_envVoltage, 136 );
lv_label_set_text(ui_envVoltage,"Voltage");
ui_object_set_themeable_style_property(ui_envVoltage, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx2);
ui_object_set_themeable_style_property(ui_envVoltage, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx2);
lv_obj_set_style_text_font(ui_envVoltage, &ui_font_InterRegular13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_envVoltageV = lv_label_create(ui_scrEnvironment);
lv_obj_set_width( ui_envVoltageV, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_envVoltageV, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_envVoltageV, -16 );
lv_obj_set_y( ui_envVoltageV, 136 );
lv_obj_set_align( ui_envVoltageV, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_envVoltageV,"1.803 V");
ui_object_set_themeable_style_property(ui_envVoltageV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx1);
ui_object_set_themeable_style_property(ui_envVoltageV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx1);
lv_obj_set_style_text_font(ui_envVoltageV, &ui_font_JetBrainsMedium14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_envStatus = lv_label_create(ui_scrEnvironment);
lv_obj_set_width( ui_envStatus, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_envStatus, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_envStatus, 16 );
lv_obj_set_y( ui_envStatus, 160 );
lv_label_set_text(ui_envStatus,"Status");
ui_object_set_themeable_style_property(ui_envStatus, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx2);
ui_object_set_themeable_style_property(ui_envStatus, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx2);
lv_obj_set_style_text_font(ui_envStatus, &ui_font_InterRegular13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_envStatusV = lv_label_create(ui_scrEnvironment);
lv_obj_set_width( ui_envStatusV, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_envStatusV, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_envStatusV, -16 );
lv_obj_set_y( ui_envStatusV, 160 );
lv_obj_set_align( ui_envStatusV, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_envStatusV,"Good");
ui_object_set_themeable_style_property(ui_envStatusV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_okg);
ui_object_set_themeable_style_property(ui_envStatusV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_okg);
lv_obj_set_style_text_font(ui_envStatusV, &ui_font_JetBrainsMedium14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_envNav = lv_obj_create(ui_scrEnvironment);
lv_obj_remove_style_all(ui_envNav);
lv_obj_set_width( ui_envNav, 320);
lv_obj_set_height( ui_envNav, 60);
lv_obj_set_x( ui_envNav, 0 );
lv_obj_set_y( ui_envNav, 180 );
lv_obj_remove_flag( ui_envNav, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_envNavLegend = lv_label_create(ui_envNav);
lv_obj_set_width( ui_envNavLegend, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_envNavLegend, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_envNavLegend, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_envNavLegend,"Push SW3 to switch screen");
ui_object_set_themeable_style_property(ui_envNavLegend, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx2);
ui_object_set_themeable_style_property(ui_envNavLegend, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx2);
lv_obj_set_style_text_font(ui_envNavLegend, &ui_font_InterRegular13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_envNavGrid = lv_image_create(ui_envNav);
lv_image_set_src(ui_envNavGrid, &ui_img_651563667);
lv_obj_set_width( ui_envNavGrid, 24);
lv_obj_set_height( ui_envNavGrid, 24);
lv_obj_set_x( ui_envNavGrid, 20 );
lv_obj_set_y( ui_envNavGrid, 26 );
lv_obj_add_flag( ui_envNavGrid, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_envNavGrid, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_envNavGrid,128);

ui_envNavTilt = lv_image_create(ui_envNav);
lv_image_set_src(ui_envNavTilt, &ui_img_563396740);
lv_obj_set_width( ui_envNavTilt, 24);
lv_obj_set_height( ui_envNavTilt, 24);
lv_obj_set_x( ui_envNavTilt, 84 );
lv_obj_set_y( ui_envNavTilt, 26 );
lv_obj_add_flag( ui_envNavTilt, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_envNavTilt, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_envNavTilt,128);

ui_envNavEnv = lv_image_create(ui_envNav);
lv_image_set_src(ui_envNavEnv, &ui_img_1090598983);
lv_obj_set_width( ui_envNavEnv, 24);
lv_obj_set_height( ui_envNavEnv, 24);
lv_obj_set_x( ui_envNavEnv, 148 );
lv_obj_set_y( ui_envNavEnv, 26 );
lv_obj_add_flag( ui_envNavEnv, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_envNavEnv, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_envNavEnv,128);
ui_object_set_themeable_style_property(ui_envNavEnv, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_acc);
ui_object_set_themeable_style_property(ui_envNavEnv, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_acc);

ui_envNavCan = lv_image_create(ui_envNav);
lv_image_set_src(ui_envNavCan, &ui_img_18748633);
lv_obj_set_width( ui_envNavCan, 24);
lv_obj_set_height( ui_envNavCan, 24);
lv_obj_set_x( ui_envNavCan, 212 );
lv_obj_set_y( ui_envNavCan, 26 );
lv_obj_add_flag( ui_envNavCan, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_envNavCan, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_envNavCan,128);

ui_envNavPower = lv_image_create(ui_envNav);
lv_image_set_src(ui_envNavPower, &ui_img_1641652374);
lv_obj_set_width( ui_envNavPower, 24);
lv_obj_set_height( ui_envNavPower, 24);
lv_obj_set_x( ui_envNavPower, 276 );
lv_obj_set_y( ui_envNavPower, 26 );
lv_obj_add_flag( ui_envNavPower, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_envNavPower, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_envNavPower,128);

}

void ui_scrEnvironment_screen_destroy(void)
{
   if (ui_scrEnvironment) lv_obj_del(ui_scrEnvironment);

// NULL screen variables
ui_scrEnvironment= NULL;
ui_envName= NULL;
ui_envHeroValue= NULL;
ui_envHerounit= NULL;
ui_div4= NULL;
ui_envSensor= NULL;
ui_envSensorV= NULL;
ui_envChannel= NULL;
ui_envChannelV= NULL;
ui_envVoltage= NULL;
ui_envVoltageV= NULL;
ui_envStatus= NULL;
ui_envStatusV= NULL;
ui_envNav= NULL;
ui_envNavLegend= NULL;
ui_envNavGrid= NULL;
ui_envNavTilt= NULL;
ui_envNavEnv= NULL;
ui_envNavCan= NULL;
ui_envNavPower= NULL;

}
