// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine

#include "../ui.h"

lv_obj_t *ui_scrTilt = NULL;lv_obj_t *ui_tiltName = NULL;lv_obj_t *ui_div3 = NULL;lv_obj_t *ui_axisXCnt = NULL;lv_obj_t *ui_axisX = NULL;lv_obj_t *ui_axisXv = NULL;lv_obj_t *ui_axisXbar = NULL;lv_obj_t *ui_axisYCnt = NULL;lv_obj_t *ui_axisY = NULL;lv_obj_t *ui_axisYv = NULL;lv_obj_t *ui_axisYbar = NULL;lv_obj_t *ui_axisZCnt = NULL;lv_obj_t *ui_axisZ = NULL;lv_obj_t *ui_axisZv = NULL;lv_obj_t *ui_axisZbar = NULL;lv_obj_t *ui_leftScale = NULL;lv_obj_t *ui_midScale = NULL;lv_obj_t *ui_rightScale = NULL;lv_obj_t *ui_tiltNav = NULL;lv_obj_t *ui_tiltNavLegend = NULL;lv_obj_t *ui_tiltNavGrid = NULL;lv_obj_t *ui_tiltNavTilt = NULL;lv_obj_t *ui_tiltNavEnv = NULL;lv_obj_t *ui_tiltNavCan = NULL;lv_obj_t *ui_tiltNavPower = NULL;
// event funtions

// build funtions

void ui_scrTilt_screen_init(void)
{
ui_scrTilt = lv_obj_create(NULL);
lv_obj_remove_flag( ui_scrTilt, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_tiltName = lv_label_create(ui_scrTilt);
lv_obj_set_width( ui_tiltName, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tiltName, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tiltName, 16 );
lv_obj_set_y( ui_tiltName, 16 );
lv_label_set_text(ui_tiltName,"TILT / MOTION");
ui_object_set_themeable_style_property(ui_tiltName, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx1);
ui_object_set_themeable_style_property(ui_tiltName, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx1);
lv_obj_set_style_text_font(ui_tiltName, &ui_font_InterMedium11, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_div3 = lv_obj_create(ui_scrTilt);
lv_obj_remove_style_all(ui_div3);
lv_obj_set_width( ui_div3, 288);
lv_obj_set_height( ui_div3, 1);
lv_obj_set_x( ui_div3, 16 );
lv_obj_set_y( ui_div3, 40 );
lv_obj_remove_flag( ui_div3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_div3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_ln0);
ui_object_set_themeable_style_property(ui_div3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_ln0);
lv_obj_set_style_border_width(ui_div3, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_axisXCnt = lv_obj_create(ui_scrTilt);
lv_obj_remove_style_all(ui_axisXCnt);
lv_obj_set_width( ui_axisXCnt, 288);
lv_obj_set_height( ui_axisXCnt, 35);
lv_obj_set_x( ui_axisXCnt, 16 );
lv_obj_set_y( ui_axisXCnt, 52 );
lv_obj_remove_flag( ui_axisXCnt, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_axisX = lv_label_create(ui_axisXCnt);
lv_obj_set_width( ui_axisX, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_axisX, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_axisX,"X");
ui_object_set_themeable_style_property(ui_axisX, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx2);
ui_object_set_themeable_style_property(ui_axisX, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx2);
lv_obj_set_style_text_font(ui_axisX, &ui_font_InterMedium11, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_axisXv = lv_label_create(ui_axisXCnt);
lv_obj_set_width( ui_axisXv, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_axisXv, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_axisXv, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_axisXv,"0.02 g");
ui_object_set_themeable_style_property(ui_axisXv, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx1);
ui_object_set_themeable_style_property(ui_axisXv, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx1);
lv_obj_set_style_text_font(ui_axisXv, &ui_font_JetBrainsMedium14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_axisXbar = lv_slider_create(ui_axisXCnt);
lv_slider_set_range(ui_axisXbar, -200,200);
lv_slider_set_mode(ui_axisXbar, LV_SLIDER_MODE_RANGE);
lv_slider_set_value( ui_axisXbar, 10, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_axisXbar)==LV_SLIDER_MODE_RANGE ) lv_slider_set_start_value( ui_axisXbar, -5, LV_ANIM_OFF);
lv_obj_set_width( ui_axisXbar, 288);
lv_obj_set_height( ui_axisXbar, 12);
lv_obj_set_x( ui_axisXbar, 0 );
lv_obj_set_y( ui_axisXbar, 20 );
lv_obj_set_align( ui_axisXbar, LV_ALIGN_TOP_MID );
ui_object_set_themeable_style_property(ui_axisXbar, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_bg2);
ui_object_set_themeable_style_property(ui_axisXbar, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_bg2);

ui_object_set_themeable_style_property(ui_axisXbar, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_acc);
ui_object_set_themeable_style_property(ui_axisXbar, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_acc);

lv_obj_set_style_pad_left(ui_axisXbar, -10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_axisXbar, -10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_axisXbar, -10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_axisXbar, -10, LV_PART_KNOB| LV_STATE_DEFAULT);

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_axisXbar,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_axisXbar, lv_obj_get_style_pad_right(ui_axisXbar,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_axisYCnt = lv_obj_create(ui_scrTilt);
lv_obj_remove_style_all(ui_axisYCnt);
lv_obj_set_width( ui_axisYCnt, 288);
lv_obj_set_height( ui_axisYCnt, 35);
lv_obj_set_x( ui_axisYCnt, 16 );
lv_obj_set_y( ui_axisYCnt, 87 );
lv_obj_remove_flag( ui_axisYCnt, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_axisY = lv_label_create(ui_axisYCnt);
lv_obj_set_width( ui_axisY, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_axisY, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_axisY,"Y");
ui_object_set_themeable_style_property(ui_axisY, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx2);
ui_object_set_themeable_style_property(ui_axisY, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx2);
lv_obj_set_style_text_font(ui_axisY, &ui_font_InterMedium11, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_axisYv = lv_label_create(ui_axisYCnt);
lv_obj_set_width( ui_axisYv, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_axisYv, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_axisYv, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_axisYv,"0.02 g");
ui_object_set_themeable_style_property(ui_axisYv, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx1);
ui_object_set_themeable_style_property(ui_axisYv, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx1);
lv_obj_set_style_text_font(ui_axisYv, &ui_font_JetBrainsMedium14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_axisYbar = lv_slider_create(ui_axisYCnt);
lv_slider_set_range(ui_axisYbar, -200,200);
lv_slider_set_mode(ui_axisYbar, LV_SLIDER_MODE_RANGE);
lv_slider_set_value( ui_axisYbar, 10, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_axisYbar)==LV_SLIDER_MODE_RANGE ) lv_slider_set_start_value( ui_axisYbar, -5, LV_ANIM_OFF);
lv_obj_set_width( ui_axisYbar, 288);
lv_obj_set_height( ui_axisYbar, 12);
lv_obj_set_x( ui_axisYbar, 0 );
lv_obj_set_y( ui_axisYbar, 20 );
lv_obj_set_align( ui_axisYbar, LV_ALIGN_TOP_MID );
ui_object_set_themeable_style_property(ui_axisYbar, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_bg2);
ui_object_set_themeable_style_property(ui_axisYbar, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_bg2);

ui_object_set_themeable_style_property(ui_axisYbar, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_acc);
ui_object_set_themeable_style_property(ui_axisYbar, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_acc);

lv_obj_set_style_pad_left(ui_axisYbar, -10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_axisYbar, -10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_axisYbar, -10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_axisYbar, -10, LV_PART_KNOB| LV_STATE_DEFAULT);

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_axisYbar,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_axisYbar, lv_obj_get_style_pad_right(ui_axisYbar,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_axisZCnt = lv_obj_create(ui_scrTilt);
lv_obj_remove_style_all(ui_axisZCnt);
lv_obj_set_width( ui_axisZCnt, 288);
lv_obj_set_height( ui_axisZCnt, 35);
lv_obj_set_x( ui_axisZCnt, 16 );
lv_obj_set_y( ui_axisZCnt, 122 );
lv_obj_remove_flag( ui_axisZCnt, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_axisZ = lv_label_create(ui_axisZCnt);
lv_obj_set_width( ui_axisZ, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_axisZ, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_axisZ,"Z");
ui_object_set_themeable_style_property(ui_axisZ, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx2);
ui_object_set_themeable_style_property(ui_axisZ, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx2);
lv_obj_set_style_text_font(ui_axisZ, &ui_font_InterMedium11, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_axisZv = lv_label_create(ui_axisZCnt);
lv_obj_set_width( ui_axisZv, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_axisZv, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_axisZv, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_axisZv,"0.02 g");
ui_object_set_themeable_style_property(ui_axisZv, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx1);
ui_object_set_themeable_style_property(ui_axisZv, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx1);
lv_obj_set_style_text_font(ui_axisZv, &ui_font_JetBrainsMedium14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_axisZbar = lv_slider_create(ui_axisZCnt);
lv_slider_set_range(ui_axisZbar, -200,200);
lv_slider_set_mode(ui_axisZbar, LV_SLIDER_MODE_RANGE);
lv_slider_set_value( ui_axisZbar, 10, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_axisZbar)==LV_SLIDER_MODE_RANGE ) lv_slider_set_start_value( ui_axisZbar, -5, LV_ANIM_OFF);
lv_obj_set_width( ui_axisZbar, 288);
lv_obj_set_height( ui_axisZbar, 12);
lv_obj_set_x( ui_axisZbar, 0 );
lv_obj_set_y( ui_axisZbar, 20 );
lv_obj_set_align( ui_axisZbar, LV_ALIGN_TOP_MID );
ui_object_set_themeable_style_property(ui_axisZbar, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_bg2);
ui_object_set_themeable_style_property(ui_axisZbar, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_bg2);

ui_object_set_themeable_style_property(ui_axisZbar, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_acc);
ui_object_set_themeable_style_property(ui_axisZbar, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_acc);

lv_obj_set_style_pad_left(ui_axisZbar, -10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_axisZbar, -10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_axisZbar, -10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_axisZbar, -10, LV_PART_KNOB| LV_STATE_DEFAULT);

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_axisZbar,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_axisZbar, lv_obj_get_style_pad_right(ui_axisZbar,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_leftScale = lv_label_create(ui_scrTilt);
lv_obj_set_width( ui_leftScale, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_leftScale, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_leftScale, 16 );
lv_obj_set_y( ui_leftScale, 160 );
lv_label_set_text(ui_leftScale,"-2g");
ui_object_set_themeable_style_property(ui_leftScale, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx2);
ui_object_set_themeable_style_property(ui_leftScale, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx2);
lv_obj_set_style_text_font(ui_leftScale, &ui_font_InterRegular13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_midScale = lv_label_create(ui_scrTilt);
lv_obj_set_width( ui_midScale, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_midScale, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_midScale, 0 );
lv_obj_set_y( ui_midScale, 160 );
lv_obj_set_align( ui_midScale, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_midScale,"0");
ui_object_set_themeable_style_property(ui_midScale, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx2);
ui_object_set_themeable_style_property(ui_midScale, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx2);
lv_obj_set_style_text_font(ui_midScale, &ui_font_InterRegular13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rightScale = lv_label_create(ui_scrTilt);
lv_obj_set_width( ui_rightScale, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_rightScale, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_rightScale, -16 );
lv_obj_set_y( ui_rightScale, 160 );
lv_obj_set_align( ui_rightScale, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_rightScale,"+2g");
ui_object_set_themeable_style_property(ui_rightScale, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx2);
ui_object_set_themeable_style_property(ui_rightScale, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx2);
lv_obj_set_style_text_font(ui_rightScale, &ui_font_InterRegular13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tiltNav = lv_obj_create(ui_scrTilt);
lv_obj_remove_style_all(ui_tiltNav);
lv_obj_set_width( ui_tiltNav, 320);
lv_obj_set_height( ui_tiltNav, 60);
lv_obj_set_x( ui_tiltNav, 0 );
lv_obj_set_y( ui_tiltNav, 180 );
lv_obj_remove_flag( ui_tiltNav, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_tiltNavLegend = lv_label_create(ui_tiltNav);
lv_obj_set_width( ui_tiltNavLegend, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tiltNavLegend, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_tiltNavLegend, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_tiltNavLegend,"Push SW3 to switch screen");
ui_object_set_themeable_style_property(ui_tiltNavLegend, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx2);
ui_object_set_themeable_style_property(ui_tiltNavLegend, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx2);
lv_obj_set_style_text_font(ui_tiltNavLegend, &ui_font_InterRegular13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tiltNavGrid = lv_image_create(ui_tiltNav);
lv_image_set_src(ui_tiltNavGrid, &ui_img_651563667);
lv_obj_set_width( ui_tiltNavGrid, 24);
lv_obj_set_height( ui_tiltNavGrid, 24);
lv_obj_set_x( ui_tiltNavGrid, 20 );
lv_obj_set_y( ui_tiltNavGrid, 26 );
lv_obj_add_flag( ui_tiltNavGrid, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_tiltNavGrid, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_tiltNavGrid,128);

ui_tiltNavTilt = lv_image_create(ui_tiltNav);
lv_image_set_src(ui_tiltNavTilt, &ui_img_563396740);
lv_obj_set_width( ui_tiltNavTilt, 24);
lv_obj_set_height( ui_tiltNavTilt, 24);
lv_obj_set_x( ui_tiltNavTilt, 84 );
lv_obj_set_y( ui_tiltNavTilt, 26 );
lv_obj_add_flag( ui_tiltNavTilt, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_tiltNavTilt, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_tiltNavTilt,128);
ui_object_set_themeable_style_property(ui_tiltNavTilt, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_acc);
ui_object_set_themeable_style_property(ui_tiltNavTilt, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_acc);

ui_tiltNavEnv = lv_image_create(ui_tiltNav);
lv_image_set_src(ui_tiltNavEnv, &ui_img_1090598983);
lv_obj_set_width( ui_tiltNavEnv, 24);
lv_obj_set_height( ui_tiltNavEnv, 24);
lv_obj_set_x( ui_tiltNavEnv, 148 );
lv_obj_set_y( ui_tiltNavEnv, 26 );
lv_obj_add_flag( ui_tiltNavEnv, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_tiltNavEnv, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_tiltNavEnv,128);

ui_tiltNavCan = lv_image_create(ui_tiltNav);
lv_image_set_src(ui_tiltNavCan, &ui_img_18748633);
lv_obj_set_width( ui_tiltNavCan, 24);
lv_obj_set_height( ui_tiltNavCan, 24);
lv_obj_set_x( ui_tiltNavCan, 212 );
lv_obj_set_y( ui_tiltNavCan, 26 );
lv_obj_add_flag( ui_tiltNavCan, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_tiltNavCan, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_tiltNavCan,128);

ui_tiltNavPower = lv_image_create(ui_tiltNav);
lv_image_set_src(ui_tiltNavPower, &ui_img_1641652374);
lv_obj_set_width( ui_tiltNavPower, 24);
lv_obj_set_height( ui_tiltNavPower, 24);
lv_obj_set_x( ui_tiltNavPower, 276 );
lv_obj_set_y( ui_tiltNavPower, 26 );
lv_obj_add_flag( ui_tiltNavPower, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_tiltNavPower, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_tiltNavPower,128);

}

void ui_scrTilt_screen_destroy(void)
{
   if (ui_scrTilt) lv_obj_del(ui_scrTilt);

// NULL screen variables
ui_scrTilt= NULL;
ui_tiltName= NULL;
ui_div3= NULL;
ui_axisXCnt= NULL;
ui_axisX= NULL;
ui_axisXv= NULL;
ui_axisXbar= NULL;
ui_axisYCnt= NULL;
ui_axisY= NULL;
ui_axisYv= NULL;
ui_axisYbar= NULL;
ui_axisZCnt= NULL;
ui_axisZ= NULL;
ui_axisZv= NULL;
ui_axisZbar= NULL;
ui_leftScale= NULL;
ui_midScale= NULL;
ui_rightScale= NULL;
ui_tiltNav= NULL;
ui_tiltNavLegend= NULL;
ui_tiltNavGrid= NULL;
ui_tiltNavTilt= NULL;
ui_tiltNavEnv= NULL;
ui_tiltNavCan= NULL;
ui_tiltNavPower= NULL;

}
