// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine

#ifndef UI_SCRTILT_H
#define UI_SCRTILT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrTilt
extern void ui_scrTilt_screen_init(void);
extern void ui_scrTilt_screen_destroy(void);
extern lv_obj_t *ui_scrTilt;
extern lv_obj_t *ui_tiltName;
extern lv_obj_t *ui_div3;
extern lv_obj_t *ui_axisXCnt;
extern lv_obj_t *ui_axisX;
extern lv_obj_t *ui_axisXv;
extern lv_obj_t *ui_axisXbar;
extern lv_obj_t *ui_axisYCnt;
extern lv_obj_t *ui_axisY;
extern lv_obj_t *ui_axisYv;
extern lv_obj_t *ui_axisYbar;
extern lv_obj_t *ui_axisZCnt;
extern lv_obj_t *ui_axisZ;
extern lv_obj_t *ui_axisZv;
extern lv_obj_t *ui_axisZbar;
extern lv_obj_t *ui_leftScale;
extern lv_obj_t *ui_midScale;
extern lv_obj_t *ui_rightScale;
extern lv_obj_t *ui_tiltNav;
extern lv_obj_t *ui_tiltNavLegend;
extern lv_obj_t *ui_tiltNavGrid;
extern lv_obj_t *ui_tiltNavTilt;
extern lv_obj_t *ui_tiltNavEnv;
extern lv_obj_t *ui_tiltNavCan;
extern lv_obj_t *ui_tiltNavPower;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

