// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine

#include "../ui.h"

lv_obj_t *ui_scrCan = NULL;lv_obj_t *ui_canName = NULL;lv_obj_t *ui_canHero = NULL;lv_obj_t *ui_div5 = NULL;lv_obj_t *ui_canFrame = NULL;lv_obj_t *ui_canFrameV = NULL;lv_obj_t *ui_canTxInterval = NULL;lv_obj_t *ui_canTxIntervalV = NULL;lv_obj_t *ui_canCount = NULL;lv_obj_t *ui_canCountV = NULL;lv_obj_t *ui_canNav = NULL;lv_obj_t *ui_canNavLegend = NULL;lv_obj_t *ui_canNavGrid = NULL;lv_obj_t *ui_canNavTilt = NULL;lv_obj_t *ui_canNavEnv = NULL;lv_obj_t *ui_canNavCan = NULL;lv_obj_t *ui_canNavPower = NULL;
// event funtions

// build funtions

void ui_scrCan_screen_init(void)
{
ui_scrCan = lv_obj_create(NULL);
lv_obj_remove_flag( ui_scrCan, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_canName = lv_label_create(ui_scrCan);
lv_obj_set_width( ui_canName, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_canName, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_canName, 16 );
lv_obj_set_y( ui_canName, 16 );
lv_label_set_text(ui_canName,"CAN");
ui_object_set_themeable_style_property(ui_canName, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx1);
ui_object_set_themeable_style_property(ui_canName, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx1);
lv_obj_set_style_text_font(ui_canName, &ui_font_InterMedium11, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_canHero = lv_label_create(ui_scrCan);
lv_obj_set_width( ui_canHero, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_canHero, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_canHero, 16 );
lv_obj_set_y( ui_canHero, 32 );
lv_label_set_text(ui_canHero,"Loopback OK");
ui_object_set_themeable_style_property(ui_canHero, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx1);
ui_object_set_themeable_style_property(ui_canHero, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx1);
lv_obj_set_style_text_font(ui_canHero, &ui_font_InterBold28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_div5 = lv_obj_create(ui_scrCan);
lv_obj_remove_style_all(ui_div5);
lv_obj_set_width( ui_div5, 288);
lv_obj_set_height( ui_div5, 1);
lv_obj_set_x( ui_div5, 16 );
lv_obj_set_y( ui_div5, 76 );
lv_obj_remove_flag( ui_div5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_div5, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_ln0);
ui_object_set_themeable_style_property(ui_div5, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_ln0);
lv_obj_set_style_border_width(ui_div5, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_canFrame = lv_label_create(ui_scrCan);
lv_obj_set_width( ui_canFrame, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_canFrame, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_canFrame, 16 );
lv_obj_set_y( ui_canFrame, 88 );
lv_label_set_text(ui_canFrame,"Frame ID");
ui_object_set_themeable_style_property(ui_canFrame, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx2);
ui_object_set_themeable_style_property(ui_canFrame, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx2);
lv_obj_set_style_text_font(ui_canFrame, &ui_font_InterRegular13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_canFrameV = lv_label_create(ui_scrCan);
lv_obj_set_width( ui_canFrameV, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_canFrameV, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_canFrameV, -16 );
lv_obj_set_y( ui_canFrameV, 88 );
lv_obj_set_align( ui_canFrameV, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_canFrameV,"0x0412");
ui_object_set_themeable_style_property(ui_canFrameV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx1);
ui_object_set_themeable_style_property(ui_canFrameV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx1);
lv_obj_set_style_text_font(ui_canFrameV, &ui_font_JetBrainsMedium14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_canTxInterval = lv_label_create(ui_scrCan);
lv_obj_set_width( ui_canTxInterval, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_canTxInterval, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_canTxInterval, 16 );
lv_obj_set_y( ui_canTxInterval, 112 );
lv_label_set_text(ui_canTxInterval,"TX Interval");
ui_object_set_themeable_style_property(ui_canTxInterval, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx2);
ui_object_set_themeable_style_property(ui_canTxInterval, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx2);
lv_obj_set_style_text_font(ui_canTxInterval, &ui_font_InterRegular13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_canTxIntervalV = lv_label_create(ui_scrCan);
lv_obj_set_width( ui_canTxIntervalV, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_canTxIntervalV, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_canTxIntervalV, -16 );
lv_obj_set_y( ui_canTxIntervalV, 112 );
lv_obj_set_align( ui_canTxIntervalV, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_canTxIntervalV,"200 ms");
ui_object_set_themeable_style_property(ui_canTxIntervalV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx1);
ui_object_set_themeable_style_property(ui_canTxIntervalV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx1);
lv_obj_set_style_text_font(ui_canTxIntervalV, &ui_font_JetBrainsMedium14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_canCount = lv_label_create(ui_scrCan);
lv_obj_set_width( ui_canCount, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_canCount, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_canCount, 16 );
lv_obj_set_y( ui_canCount, 136 );
lv_label_set_text(ui_canCount,"TX / RX count");
ui_object_set_themeable_style_property(ui_canCount, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx2);
ui_object_set_themeable_style_property(ui_canCount, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx2);
lv_obj_set_style_text_font(ui_canCount, &ui_font_InterRegular13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_canCountV = lv_label_create(ui_scrCan);
lv_obj_set_width( ui_canCountV, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_canCountV, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_canCountV, -16 );
lv_obj_set_y( ui_canCountV, 136 );
lv_obj_set_align( ui_canCountV, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_canCountV,"348 / 348");
ui_object_set_themeable_style_property(ui_canCountV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx1);
ui_object_set_themeable_style_property(ui_canCountV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx1);
lv_obj_set_style_text_font(ui_canCountV, &ui_font_JetBrainsMedium14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_canNav = lv_obj_create(ui_scrCan);
lv_obj_remove_style_all(ui_canNav);
lv_obj_set_width( ui_canNav, 320);
lv_obj_set_height( ui_canNav, 60);
lv_obj_set_x( ui_canNav, 0 );
lv_obj_set_y( ui_canNav, 180 );
lv_obj_remove_flag( ui_canNav, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_canNavLegend = lv_label_create(ui_canNav);
lv_obj_set_width( ui_canNavLegend, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_canNavLegend, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_canNavLegend, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_canNavLegend,"Push SW3 to switch screen");
ui_object_set_themeable_style_property(ui_canNavLegend, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx2);
ui_object_set_themeable_style_property(ui_canNavLegend, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx2);
lv_obj_set_style_text_font(ui_canNavLegend, &ui_font_InterRegular13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_canNavGrid = lv_image_create(ui_canNav);
lv_image_set_src(ui_canNavGrid, &ui_img_651563667);
lv_obj_set_width( ui_canNavGrid, 24);
lv_obj_set_height( ui_canNavGrid, 24);
lv_obj_set_x( ui_canNavGrid, 20 );
lv_obj_set_y( ui_canNavGrid, 26 );
lv_obj_add_flag( ui_canNavGrid, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_canNavGrid, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_canNavGrid,128);

ui_canNavTilt = lv_image_create(ui_canNav);
lv_image_set_src(ui_canNavTilt, &ui_img_563396740);
lv_obj_set_width( ui_canNavTilt, 24);
lv_obj_set_height( ui_canNavTilt, 24);
lv_obj_set_x( ui_canNavTilt, 84 );
lv_obj_set_y( ui_canNavTilt, 26 );
lv_obj_add_flag( ui_canNavTilt, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_canNavTilt, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_canNavTilt,128);

ui_canNavEnv = lv_image_create(ui_canNav);
lv_image_set_src(ui_canNavEnv, &ui_img_1090598983);
lv_obj_set_width( ui_canNavEnv, 24);
lv_obj_set_height( ui_canNavEnv, 24);
lv_obj_set_x( ui_canNavEnv, 148 );
lv_obj_set_y( ui_canNavEnv, 26 );
lv_obj_add_flag( ui_canNavEnv, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_canNavEnv, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_canNavEnv,128);

ui_canNavCan = lv_image_create(ui_canNav);
lv_image_set_src(ui_canNavCan, &ui_img_18748633);
lv_obj_set_width( ui_canNavCan, 24);
lv_obj_set_height( ui_canNavCan, 24);
lv_obj_set_x( ui_canNavCan, 212 );
lv_obj_set_y( ui_canNavCan, 26 );
lv_obj_add_flag( ui_canNavCan, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_canNavCan, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_canNavCan,128);
ui_object_set_themeable_style_property(ui_canNavCan, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_acc);
ui_object_set_themeable_style_property(ui_canNavCan, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_acc);

ui_canNavPower = lv_image_create(ui_canNav);
lv_image_set_src(ui_canNavPower, &ui_img_1641652374);
lv_obj_set_width( ui_canNavPower, 24);
lv_obj_set_height( ui_canNavPower, 24);
lv_obj_set_x( ui_canNavPower, 276 );
lv_obj_set_y( ui_canNavPower, 26 );
lv_obj_add_flag( ui_canNavPower, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_canNavPower, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_canNavPower,128);

}

void ui_scrCan_screen_destroy(void)
{
   if (ui_scrCan) lv_obj_del(ui_scrCan);

// NULL screen variables
ui_scrCan= NULL;
ui_canName= NULL;
ui_canHero= NULL;
ui_div5= NULL;
ui_canFrame= NULL;
ui_canFrameV= NULL;
ui_canTxInterval= NULL;
ui_canTxIntervalV= NULL;
ui_canCount= NULL;
ui_canCountV= NULL;
ui_canNav= NULL;
ui_canNavLegend= NULL;
ui_canNavGrid= NULL;
ui_canNavTilt= NULL;
ui_canNavEnv= NULL;
ui_canNavCan= NULL;
ui_canNavPower= NULL;

}
