// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine

#include "../ui.h"

lv_obj_t *ui_scrOverview = NULL;lv_obj_t *ui_overviewName = NULL;lv_obj_t *ui_overviewUptime = NULL;lv_obj_t *ui_overviewClkImg = NULL;lv_obj_t *ui_div1 = NULL;lv_obj_t *ui_overviewStatusHero = NULL;lv_obj_t *ui_overviewStatus = NULL;lv_obj_t *ui_overviewStatusContainer = NULL;lv_obj_t *ui_overviewMqHero = NULL;lv_obj_t *ui_overviewMqStatus = NULL;lv_obj_t *ui_overviewCanHero = NULL;lv_obj_t *ui_overviewCanStatus = NULL;lv_obj_t *ui_overviewTiltHero = NULL;lv_obj_t *ui_overviewTiltStatus = NULL;lv_obj_t *ui_div2 = NULL;lv_obj_t *ui_overviewDevice = NULL;lv_obj_t *ui_overviewVersion = NULL;lv_obj_t *ui_overviewNav = NULL;lv_obj_t *ui_overviewNavLegend = NULL;lv_obj_t *ui_overviewNavGrid = NULL;lv_obj_t *ui_overviewNavTilt = NULL;lv_obj_t *ui_overviewNavEnv = NULL;lv_obj_t *ui_overviewNavCan = NULL;lv_obj_t *ui_overviewNavSleep = NULL;
// event funtions

// build funtions

void ui_scrOverview_screen_init(void)
{
ui_scrOverview = lv_obj_create(NULL);
lv_obj_remove_flag( ui_scrOverview, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_overviewName = lv_label_create(ui_scrOverview);
lv_obj_set_width( ui_overviewName, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_overviewName, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_overviewName, 16 );
lv_obj_set_y( ui_overviewName, 16 );
lv_label_set_text(ui_overviewName,"SENSOR HUB");
ui_object_set_themeable_style_property(ui_overviewName, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx1);
ui_object_set_themeable_style_property(ui_overviewName, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx1);
lv_obj_set_style_text_font(ui_overviewName, &ui_font_InterSemiBold16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_overviewUptime = lv_label_create(ui_scrOverview);
lv_obj_set_width( ui_overviewUptime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_overviewUptime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_overviewUptime, 240 );
lv_obj_set_y( ui_overviewUptime, 21 );
lv_label_set_text(ui_overviewUptime,"00:00:00");
ui_object_set_themeable_style_property(ui_overviewUptime, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx2);
ui_object_set_themeable_style_property(ui_overviewUptime, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx2);
lv_obj_set_style_text_font(ui_overviewUptime, &ui_font_InterMedium11, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_overviewClkImg = lv_image_create(ui_scrOverview);
lv_image_set_src(ui_overviewClkImg, &ui_img_1390009267);
lv_obj_set_width( ui_overviewClkImg, 12);
lv_obj_set_height( ui_overviewClkImg, 12);
lv_obj_set_x( ui_overviewClkImg, 220 );
lv_obj_set_y( ui_overviewClkImg, 20 );
lv_obj_add_flag( ui_overviewClkImg, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_overviewClkImg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_overviewClkImg,80);

ui_div1 = lv_obj_create(ui_scrOverview);
lv_obj_remove_style_all(ui_div1);
lv_obj_set_width( ui_div1, 288);
lv_obj_set_height( ui_div1, 1);
lv_obj_set_x( ui_div1, 16 );
lv_obj_set_y( ui_div1, 44 );
lv_obj_remove_flag( ui_div1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_div1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_ln0);
ui_object_set_themeable_style_property(ui_div1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_ln0);
lv_obj_set_style_border_width(ui_div1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_overviewStatusHero = lv_label_create(ui_scrOverview);
lv_obj_set_width( ui_overviewStatusHero, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_overviewStatusHero, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_overviewStatusHero, 16 );
lv_obj_set_y( ui_overviewStatusHero, 56 );
lv_label_set_text(ui_overviewStatusHero,"STATUS");
ui_object_set_themeable_style_property(ui_overviewStatusHero, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx2);
ui_object_set_themeable_style_property(ui_overviewStatusHero, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx2);
lv_obj_set_style_text_font(ui_overviewStatusHero, &ui_font_InterMedium11, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_overviewStatus = lv_label_create(ui_scrOverview);
lv_obj_set_width( ui_overviewStatus, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_overviewStatus, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_overviewStatus, 16 );
lv_obj_set_y( ui_overviewStatus, 70 );
lv_label_set_text(ui_overviewStatus,"NORMAL");
ui_object_set_themeable_style_property(ui_overviewStatus, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_okg);
ui_object_set_themeable_style_property(ui_overviewStatus, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_okg);
lv_obj_set_style_text_font(ui_overviewStatus, &ui_font_InterBold28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_overviewStatusContainer = lv_obj_create(ui_scrOverview);
lv_obj_remove_style_all(ui_overviewStatusContainer);
lv_obj_set_width( ui_overviewStatusContainer, 288);
lv_obj_set_height( ui_overviewStatusContainer, 14);
lv_obj_set_x( ui_overviewStatusContainer, 16 );
lv_obj_set_y( ui_overviewStatusContainer, 104 );
lv_obj_remove_flag( ui_overviewStatusContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_overviewMqHero = lv_label_create(ui_overviewStatusContainer);
lv_obj_set_width( ui_overviewMqHero, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_overviewMqHero, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_overviewMqHero, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_overviewMqHero,"MQx");
ui_object_set_themeable_style_property(ui_overviewMqHero, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx2);
ui_object_set_themeable_style_property(ui_overviewMqHero, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx2);
lv_obj_set_style_text_font(ui_overviewMqHero, &ui_font_InterRegular13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_overviewMqStatus = lv_label_create(ui_overviewStatusContainer);
lv_obj_set_width( ui_overviewMqStatus, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_overviewMqStatus, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_overviewMqStatus, 34 );
lv_obj_set_y( ui_overviewMqStatus, 0 );
lv_obj_set_align( ui_overviewMqStatus, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_overviewMqStatus,"available");
ui_object_set_themeable_style_property(ui_overviewMqStatus, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_okg);
ui_object_set_themeable_style_property(ui_overviewMqStatus, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_okg);
lv_obj_set_style_text_font(ui_overviewMqStatus, &ui_font_InterRegular13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_overviewCanHero = lv_label_create(ui_overviewStatusContainer);
lv_obj_set_width( ui_overviewCanHero, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_overviewCanHero, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_overviewCanHero, 93 );
lv_obj_set_y( ui_overviewCanHero, 0 );
lv_obj_set_align( ui_overviewCanHero, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_overviewCanHero,"| CAN");
ui_object_set_themeable_style_property(ui_overviewCanHero, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx2);
ui_object_set_themeable_style_property(ui_overviewCanHero, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx2);
lv_obj_set_style_text_font(ui_overviewCanHero, &ui_font_InterRegular13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_overviewCanStatus = lv_label_create(ui_overviewStatusContainer);
lv_obj_set_width( ui_overviewCanStatus, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_overviewCanStatus, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_overviewCanStatus, 134 );
lv_obj_set_y( ui_overviewCanStatus, 0 );
lv_obj_set_align( ui_overviewCanStatus, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_overviewCanStatus,"available");
ui_object_set_themeable_style_property(ui_overviewCanStatus, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_okg);
ui_object_set_themeable_style_property(ui_overviewCanStatus, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_okg);
lv_obj_set_style_text_font(ui_overviewCanStatus, &ui_font_InterRegular13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_overviewTiltHero = lv_label_create(ui_overviewStatusContainer);
lv_obj_set_width( ui_overviewTiltHero, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_overviewTiltHero, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_overviewTiltHero, 192 );
lv_obj_set_y( ui_overviewTiltHero, 0 );
lv_obj_set_align( ui_overviewTiltHero, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_overviewTiltHero,"| Tilt");
ui_object_set_themeable_style_property(ui_overviewTiltHero, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx2);
ui_object_set_themeable_style_property(ui_overviewTiltHero, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx2);
lv_obj_set_style_text_font(ui_overviewTiltHero, &ui_font_InterRegular13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_overviewTiltStatus = lv_label_create(ui_overviewStatusContainer);
lv_obj_set_width( ui_overviewTiltStatus, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_overviewTiltStatus, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_overviewTiltStatus, 223 );
lv_obj_set_y( ui_overviewTiltStatus, 0 );
lv_obj_set_align( ui_overviewTiltStatus, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_overviewTiltStatus,"available");
ui_object_set_themeable_style_property(ui_overviewTiltStatus, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_okg);
ui_object_set_themeable_style_property(ui_overviewTiltStatus, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_okg);
lv_obj_set_style_text_font(ui_overviewTiltStatus, &ui_font_InterRegular13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_div2 = lv_obj_create(ui_scrOverview);
lv_obj_remove_style_all(ui_div2);
lv_obj_set_width( ui_div2, 288);
lv_obj_set_height( ui_div2, 1);
lv_obj_set_x( ui_div2, 16 );
lv_obj_set_y( ui_div2, 128 );
lv_obj_remove_flag( ui_div2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_div2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_ln0);
ui_object_set_themeable_style_property(ui_div2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_ln0);
lv_obj_set_style_border_width(ui_div2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_overviewDevice = lv_label_create(ui_scrOverview);
lv_obj_set_width( ui_overviewDevice, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_overviewDevice, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_overviewDevice, 16 );
lv_obj_set_y( ui_overviewDevice, 140 );
lv_label_set_text(ui_overviewDevice,"DEVICE");
ui_object_set_themeable_style_property(ui_overviewDevice, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx2);
ui_object_set_themeable_style_property(ui_overviewDevice, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx2);
lv_obj_set_style_text_font(ui_overviewDevice, &ui_font_InterMedium11, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_overviewVersion = lv_label_create(ui_scrOverview);
lv_obj_set_width( ui_overviewVersion, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_overviewVersion, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_overviewVersion, 16 );
lv_obj_set_y( ui_overviewVersion, 154 );
lv_label_set_text(ui_overviewVersion,"FRDM-MCXN236 - fw v0.3.1");
ui_object_set_themeable_style_property(ui_overviewVersion, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx1);
ui_object_set_themeable_style_property(ui_overviewVersion, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx1);
lv_obj_set_style_text_font(ui_overviewVersion, &ui_font_JetBrainsMedium14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_overviewNav = lv_obj_create(ui_scrOverview);
lv_obj_remove_style_all(ui_overviewNav);
lv_obj_set_width( ui_overviewNav, 320);
lv_obj_set_height( ui_overviewNav, 60);
lv_obj_set_x( ui_overviewNav, 0 );
lv_obj_set_y( ui_overviewNav, 180 );
lv_obj_remove_flag( ui_overviewNav, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_overviewNavLegend = lv_label_create(ui_overviewNav);
lv_obj_set_width( ui_overviewNavLegend, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_overviewNavLegend, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_overviewNavLegend, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_overviewNavLegend,"Push SW3 to switch screen");
ui_object_set_themeable_style_property(ui_overviewNavLegend, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx2);
ui_object_set_themeable_style_property(ui_overviewNavLegend, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx2);
lv_obj_set_style_text_font(ui_overviewNavLegend, &ui_font_InterRegular13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_overviewNavGrid = lv_image_create(ui_overviewNav);
lv_image_set_src(ui_overviewNavGrid, &ui_img_651563667);
lv_obj_set_width( ui_overviewNavGrid, 24);
lv_obj_set_height( ui_overviewNavGrid, 24);
lv_obj_set_x( ui_overviewNavGrid, 20 );
lv_obj_set_y( ui_overviewNavGrid, 26 );
lv_obj_add_flag( ui_overviewNavGrid, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_overviewNavGrid, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_overviewNavGrid,128);
ui_object_set_themeable_style_property(ui_overviewNavGrid, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_acc);
ui_object_set_themeable_style_property(ui_overviewNavGrid, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_acc);

ui_overviewNavTilt = lv_image_create(ui_overviewNav);
lv_image_set_src(ui_overviewNavTilt, &ui_img_563396740);
lv_obj_set_width( ui_overviewNavTilt, 24);
lv_obj_set_height( ui_overviewNavTilt, 24);
lv_obj_set_x( ui_overviewNavTilt, 84 );
lv_obj_set_y( ui_overviewNavTilt, 26 );
lv_obj_add_flag( ui_overviewNavTilt, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_overviewNavTilt, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_overviewNavTilt,128);

ui_overviewNavEnv = lv_image_create(ui_overviewNav);
lv_image_set_src(ui_overviewNavEnv, &ui_img_1090598983);
lv_obj_set_width( ui_overviewNavEnv, 24);
lv_obj_set_height( ui_overviewNavEnv, 24);
lv_obj_set_x( ui_overviewNavEnv, 148 );
lv_obj_set_y( ui_overviewNavEnv, 26 );
lv_obj_add_flag( ui_overviewNavEnv, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_overviewNavEnv, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_overviewNavEnv,128);

ui_overviewNavCan = lv_image_create(ui_overviewNav);
lv_image_set_src(ui_overviewNavCan, &ui_img_18748633);
lv_obj_set_width( ui_overviewNavCan, 24);
lv_obj_set_height( ui_overviewNavCan, 24);
lv_obj_set_x( ui_overviewNavCan, 212 );
lv_obj_set_y( ui_overviewNavCan, 26 );
lv_obj_add_flag( ui_overviewNavCan, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_overviewNavCan, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_overviewNavCan,128);

ui_overviewNavSleep = lv_image_create(ui_overviewNav);
lv_image_set_src(ui_overviewNavSleep, &ui_img_1641652374);
lv_obj_set_width( ui_overviewNavSleep, 24);
lv_obj_set_height( ui_overviewNavSleep, 24);
lv_obj_set_x( ui_overviewNavSleep, 276 );
lv_obj_set_y( ui_overviewNavSleep, 26 );
lv_obj_add_flag( ui_overviewNavSleep, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_overviewNavSleep, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_overviewNavSleep,128);

}

void ui_scrOverview_screen_destroy(void)
{
   if (ui_scrOverview) lv_obj_del(ui_scrOverview);

// NULL screen variables
ui_scrOverview= NULL;
ui_overviewName= NULL;
ui_overviewUptime= NULL;
ui_overviewClkImg= NULL;
ui_div1= NULL;
ui_overviewStatusHero= NULL;
ui_overviewStatus= NULL;
ui_overviewStatusContainer= NULL;
ui_overviewMqHero= NULL;
ui_overviewMqStatus= NULL;
ui_overviewCanHero= NULL;
ui_overviewCanStatus= NULL;
ui_overviewTiltHero= NULL;
ui_overviewTiltStatus= NULL;
ui_div2= NULL;
ui_overviewDevice= NULL;
ui_overviewVersion= NULL;
ui_overviewNav= NULL;
ui_overviewNavLegend= NULL;
ui_overviewNavGrid= NULL;
ui_overviewNavTilt= NULL;
ui_overviewNavEnv= NULL;
ui_overviewNavCan= NULL;
ui_overviewNavSleep= NULL;

}
