// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine

#include "../ui.h"

lv_obj_t *ui_scrPower = NULL;lv_obj_t *ui_powerIcon = NULL;lv_obj_t *ui_powerHero = NULL;lv_obj_t *ui_powerInstructions = NULL;lv_obj_t *ui_powerDiscaimer = NULL;lv_obj_t *ui_powerNav = NULL;lv_obj_t *ui_powerNavLegend = NULL;lv_obj_t *ui_powerNavGrid = NULL;lv_obj_t *ui_powerNavTilt = NULL;lv_obj_t *ui_powerNavEnv = NULL;lv_obj_t *ui_powerNavCan = NULL;lv_obj_t *ui_powerNavPower = NULL;
// event funtions

// build funtions

void ui_scrPower_screen_init(void)
{
ui_scrPower = lv_obj_create(NULL);
lv_obj_remove_flag( ui_scrPower, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_powerIcon = lv_image_create(ui_scrPower);
lv_image_set_src(ui_powerIcon, &ui_img_1641652374);
lv_obj_set_width( ui_powerIcon, 48);
lv_obj_set_height( ui_powerIcon, 48);
lv_obj_set_x( ui_powerIcon, 0 );
lv_obj_set_y( ui_powerIcon, 26 );
lv_obj_set_align( ui_powerIcon, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_powerIcon, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_powerIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_powerIcon, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_acc);
ui_object_set_themeable_style_property(ui_powerIcon, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_acc);

ui_powerHero = lv_label_create(ui_scrPower);
lv_obj_set_width( ui_powerHero, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_powerHero, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_powerHero, 0 );
lv_obj_set_y( ui_powerHero, 80 );
lv_obj_set_align( ui_powerHero, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_powerHero,"AWAKE");
ui_object_set_themeable_style_property(ui_powerHero, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx1);
ui_object_set_themeable_style_property(ui_powerHero, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx1);
lv_obj_set_style_text_font(ui_powerHero, &ui_font_InterSemiBold16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_powerInstructions = lv_label_create(ui_scrPower);
lv_obj_set_width( ui_powerInstructions, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_powerInstructions, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_powerInstructions, 0 );
lv_obj_set_y( ui_powerInstructions, 102 );
lv_obj_set_align( ui_powerInstructions, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_powerInstructions,"Push SW2 to sleep");
ui_object_set_themeable_style_property(ui_powerInstructions, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx2);
ui_object_set_themeable_style_property(ui_powerInstructions, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx2);
lv_obj_set_style_text_font(ui_powerInstructions, &ui_font_InterRegular13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_powerDiscaimer = lv_label_create(ui_scrPower);
lv_obj_set_width( ui_powerDiscaimer, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_powerDiscaimer, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_powerDiscaimer, 0 );
lv_obj_set_y( ui_powerDiscaimer, 124 );
lv_obj_set_align( ui_powerDiscaimer, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_powerDiscaimer,"Pauses display, sampling, and CAN telemetry.\nSW2 or motion wakes it.");
ui_object_set_themeable_style_property(ui_powerDiscaimer, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx2);
ui_object_set_themeable_style_property(ui_powerDiscaimer, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx2);
lv_obj_set_style_text_align(ui_powerDiscaimer, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_powerDiscaimer, &ui_font_InterRegular13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_powerNav = lv_obj_create(ui_scrPower);
lv_obj_remove_style_all(ui_powerNav);
lv_obj_set_width( ui_powerNav, 320);
lv_obj_set_height( ui_powerNav, 52);
lv_obj_set_x( ui_powerNav, 0 );
lv_obj_set_y( ui_powerNav, 188 );
lv_obj_remove_flag( ui_powerNav, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_powerNavLegend = lv_label_create(ui_powerNav);
lv_obj_set_width( ui_powerNavLegend, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_powerNavLegend, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_powerNavLegend, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_powerNavLegend,"Push SW3 to switch screen");
ui_object_set_themeable_style_property(ui_powerNavLegend, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx2);
ui_object_set_themeable_style_property(ui_powerNavLegend, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx2);
lv_obj_set_style_text_font(ui_powerNavLegend, &ui_font_InterRegular13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_powerNavGrid = lv_image_create(ui_powerNav);
lv_image_set_src(ui_powerNavGrid, &ui_img_651563667);
lv_obj_set_width( ui_powerNavGrid, 24);
lv_obj_set_height( ui_powerNavGrid, 24);
lv_obj_set_x( ui_powerNavGrid, 20 );
lv_obj_set_y( ui_powerNavGrid, 18 );
lv_obj_add_flag( ui_powerNavGrid, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_powerNavGrid, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_powerNavGrid,128);

ui_powerNavTilt = lv_image_create(ui_powerNav);
lv_image_set_src(ui_powerNavTilt, &ui_img_563396740);
lv_obj_set_width( ui_powerNavTilt, 24);
lv_obj_set_height( ui_powerNavTilt, 24);
lv_obj_set_x( ui_powerNavTilt, 84 );
lv_obj_set_y( ui_powerNavTilt, 18 );
lv_obj_add_flag( ui_powerNavTilt, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_powerNavTilt, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_powerNavTilt,128);

ui_powerNavEnv = lv_image_create(ui_powerNav);
lv_image_set_src(ui_powerNavEnv, &ui_img_1090598983);
lv_obj_set_width( ui_powerNavEnv, 24);
lv_obj_set_height( ui_powerNavEnv, 24);
lv_obj_set_x( ui_powerNavEnv, 148 );
lv_obj_set_y( ui_powerNavEnv, 18 );
lv_obj_add_flag( ui_powerNavEnv, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_powerNavEnv, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_powerNavEnv,128);

ui_powerNavCan = lv_image_create(ui_powerNav);
lv_image_set_src(ui_powerNavCan, &ui_img_18748633);
lv_obj_set_width( ui_powerNavCan, 24);
lv_obj_set_height( ui_powerNavCan, 24);
lv_obj_set_x( ui_powerNavCan, 212 );
lv_obj_set_y( ui_powerNavCan, 18 );
lv_obj_add_flag( ui_powerNavCan, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_powerNavCan, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_powerNavCan,128);

ui_powerNavPower = lv_image_create(ui_powerNav);
lv_image_set_src(ui_powerNavPower, &ui_img_1641652374);
lv_obj_set_width( ui_powerNavPower, 24);
lv_obj_set_height( ui_powerNavPower, 24);
lv_obj_set_x( ui_powerNavPower, 276 );
lv_obj_set_y( ui_powerNavPower, 18 );
lv_obj_add_flag( ui_powerNavPower, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_powerNavPower, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_powerNavPower,128);
ui_object_set_themeable_style_property(ui_powerNavPower, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_acc);
ui_object_set_themeable_style_property(ui_powerNavPower, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_acc);

}

void ui_scrPower_screen_destroy(void)
{
   if (ui_scrPower) lv_obj_del(ui_scrPower);

// NULL screen variables
ui_scrPower= NULL;
ui_powerIcon= NULL;
ui_powerHero= NULL;
ui_powerInstructions= NULL;
ui_powerDiscaimer= NULL;
ui_powerNav= NULL;
ui_powerNavLegend= NULL;
ui_powerNavGrid= NULL;
ui_powerNavTilt= NULL;
ui_powerNavEnv= NULL;
ui_powerNavCan= NULL;
ui_powerNavPower= NULL;

}
