// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine

#ifndef UI_SCRCAN_H
#define UI_SCRCAN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrCan
extern void ui_scrCan_screen_init(void);
extern void ui_scrCan_screen_destroy(void);
extern lv_obj_t *ui_scrCan;
extern lv_obj_t *ui_canName;
extern lv_obj_t *ui_canHero;
extern lv_obj_t *ui_div5;
extern lv_obj_t *ui_canFrame;
extern lv_obj_t *ui_canFrameV;
extern lv_obj_t *ui_canTxInterval;
extern lv_obj_t *ui_canTxIntervalV;
extern lv_obj_t *ui_canCount;
extern lv_obj_t *ui_canCountV;
extern lv_obj_t *ui_canNav;
extern lv_obj_t *ui_canNavLegend;
extern lv_obj_t *ui_canNavGrid;
extern lv_obj_t *ui_canNavTilt;
extern lv_obj_t *ui_canNavEnv;
extern lv_obj_t *ui_canNavCan;
extern lv_obj_t *ui_canNavPower;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

