// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine

#ifndef UI_SCRSPLASH_H
#define UI_SCRSPLASH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrSplash
extern void ui_scrSplash_screen_init(void);
extern void ui_scrSplash_screen_destroy(void);
extern lv_obj_t *ui_scrSplash;
extern lv_obj_t *ui_splashIcon;
extern lv_obj_t *ui_splashName;
extern lv_obj_t *ui_splashVersion;
extern lv_obj_t *ui_splashLegend;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

