// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine

#ifndef UI_SCROVERVIEW_H
#define UI_SCROVERVIEW_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrOverview
extern void ui_scrOverview_screen_init(void);
extern void ui_scrOverview_screen_destroy(void);
extern lv_obj_t *ui_scrOverview;
extern lv_obj_t *ui_overviewName;
extern lv_obj_t *ui_overviewUptime;
extern lv_obj_t *ui_overviewClkImg;
extern lv_obj_t *ui_div1;
extern lv_obj_t *ui_overviewStatusHero;
extern lv_obj_t *ui_overviewStatus;
extern lv_obj_t *ui_overviewStatusContainer;
extern lv_obj_t *ui_overviewMqHero;
extern lv_obj_t *ui_overviewMqStatus;
extern lv_obj_t *ui_overviewCanHero;
extern lv_obj_t *ui_overviewCanStatus;
extern lv_obj_t *ui_overviewTiltHero;
extern lv_obj_t *ui_overviewTiltStatus;
extern lv_obj_t *ui_div2;
extern lv_obj_t *ui_overviewDevice;
extern lv_obj_t *ui_overviewVersion;
extern lv_obj_t *ui_overviewNav;
extern lv_obj_t *ui_overviewNavLegend;
extern lv_obj_t *ui_overviewNavGrid;
extern lv_obj_t *ui_overviewNavTilt;
extern lv_obj_t *ui_overviewNavEnv;
extern lv_obj_t *ui_overviewNavCan;
extern lv_obj_t *ui_overviewNavSleep;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

