// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine

#include "../ui.h"

lv_obj_t *ui_scrSplash = NULL;lv_obj_t *ui_splashIcon = NULL;lv_obj_t *ui_splashName = NULL;lv_obj_t *ui_splashVersion = NULL;lv_obj_t *ui_splashLegend = NULL;
// event funtions

// build funtions

void ui_scrSplash_screen_init(void)
{
ui_scrSplash = lv_obj_create(NULL);
lv_obj_remove_flag( ui_scrSplash, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_splashIcon = lv_image_create(ui_scrSplash);
lv_image_set_src(ui_splashIcon, &ui_img_651563667);
lv_obj_set_width( ui_splashIcon, 40);
lv_obj_set_height( ui_splashIcon, 40);
lv_obj_set_x( ui_splashIcon, 0 );
lv_obj_set_y( ui_splashIcon, 76 );
lv_obj_set_align( ui_splashIcon, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_splashIcon, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_splashIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_splashIcon, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_acc);
ui_object_set_themeable_style_property(ui_splashIcon, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_acc);

ui_splashName = lv_label_create(ui_scrSplash);
lv_obj_set_width( ui_splashName, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_splashName, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_splashName, 0 );
lv_obj_set_y( ui_splashName, 128 );
lv_obj_set_align( ui_splashName, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_splashName,"SENSOR HUB");
ui_object_set_themeable_style_property(ui_splashName, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx1);
ui_object_set_themeable_style_property(ui_splashName, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx1);
lv_obj_set_style_text_font(ui_splashName, &ui_font_InterSemiBold16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_splashVersion = lv_label_create(ui_scrSplash);
lv_obj_set_width( ui_splashVersion, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_splashVersion, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_splashVersion, 0 );
lv_obj_set_y( ui_splashVersion, 150 );
lv_obj_set_align( ui_splashVersion, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_splashVersion,"FRDM-MCXN236 - v0.3.1");
ui_object_set_themeable_style_property(ui_splashVersion, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx2);
ui_object_set_themeable_style_property(ui_splashVersion, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx2);
lv_obj_set_style_text_font(ui_splashVersion, &ui_font_JetBrainsMedium14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_splashLegend = lv_label_create(ui_scrSplash);
lv_obj_set_width( ui_splashLegend, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_splashLegend, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_splashLegend, 0 );
lv_obj_set_y( ui_splashLegend, 206 );
lv_obj_set_align( ui_splashLegend, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_splashLegend,"Press any key to dismiss");
ui_object_set_themeable_style_property(ui_splashLegend, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_tx2);
ui_object_set_themeable_style_property(ui_splashLegend, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_tx2);
lv_obj_set_style_text_font(ui_splashLegend, &ui_font_InterRegular13, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_scrSplash_screen_destroy(void)
{
   if (ui_scrSplash) lv_obj_del(ui_scrSplash);

// NULL screen variables
ui_scrSplash= NULL;
ui_splashIcon= NULL;
ui_splashName= NULL;
ui_splashVersion= NULL;
ui_splashLegend= NULL;

}
