// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine

#ifndef UI_SCRPOWER_H
#define UI_SCRPOWER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrPower
extern void ui_scrPower_screen_init(void);
extern void ui_scrPower_screen_destroy(void);
extern lv_obj_t *ui_scrPower;
extern lv_obj_t *ui_powerIcon;
extern lv_obj_t *ui_powerHero;
extern lv_obj_t *ui_powerInstructions;
extern lv_obj_t *ui_powerDiscaimer;
extern lv_obj_t *ui_powerNav;
extern lv_obj_t *ui_powerNavLegend;
extern lv_obj_t *ui_powerNavGrid;
extern lv_obj_t *ui_powerNavTilt;
extern lv_obj_t *ui_powerNavEnv;
extern lv_obj_t *ui_powerNavCan;
extern lv_obj_t *ui_powerNavPower;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

