// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine

#ifndef UI_SCRENVIRONMENT_H
#define UI_SCRENVIRONMENT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrEnvironment
extern void ui_scrEnvironment_screen_init(void);
extern void ui_scrEnvironment_screen_destroy(void);
extern lv_obj_t *ui_scrEnvironment;
extern lv_obj_t *ui_envName;
extern lv_obj_t *ui_envHeroValue;
extern lv_obj_t *ui_envHerounit;
extern lv_obj_t *ui_div4;
extern lv_obj_t *ui_envSensor;
extern lv_obj_t *ui_envSensorV;
extern lv_obj_t *ui_envChannel;
extern lv_obj_t *ui_envChannelV;
extern lv_obj_t *ui_envVoltage;
extern lv_obj_t *ui_envVoltageV;
extern lv_obj_t *ui_envStatus;
extern lv_obj_t *ui_envStatusV;
extern lv_obj_t *ui_envNav;
extern lv_obj_t *ui_envNavLegend;
extern lv_obj_t *ui_envNavGrid;
extern lv_obj_t *ui_envNavTilt;
extern lv_obj_t *ui_envNavEnv;
extern lv_obj_t *ui_envNavCan;
extern lv_obj_t *ui_envNavPower;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

