CONFIG_MCUBOOT_SERIAL=y
CONFIG_BOOT_SERIAL_UART=y
CONFIG_BOOT_SERIAL_ENTRANCE_GPIO=y

# Serial recovery and the console share LPUART4
CONFIG_UART_CONSOLE=n
CONFIG_BOOT_SERIAL_NO_APPLICATION=y
CONFIG_BOOT_SERIAL_UNALIGNED_BUFFER_SIZE=128

# Green LED on while MCUboot is in serial recovery
CONFIG_MCUBOOT_INDICATION_LED=y
