// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine

#ifndef _SQUARELINE_UI_H
#define _SQUARELINE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_scrSplash.h"
#include "screens/ui_scrOverview.h"
#include "screens/ui_scrTilt.h"
#include "screens/ui_scrEnvironment.h"
#include "screens/ui_scrCan.h"
#include "screens/ui_scrPower.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_651563667);   // assets/icons/ic-grid.png
LV_IMG_DECLARE( ui_img_1390009267);   // assets/icons/ic-clock.png
LV_IMG_DECLARE( ui_img_563396740);   // assets/icons/ic-tilt.png
LV_IMG_DECLARE( ui_img_1090598983);   // assets/icons/ic-leaf.png
LV_IMG_DECLARE( ui_img_18748633);   // assets/icons/ic-can.png
LV_IMG_DECLARE( ui_img_1641652374);   // assets/icons/ic-power.png

// FONTS
LV_FONT_DECLARE( ui_font_InterBold28);
LV_FONT_DECLARE( ui_font_InterMedium11);
LV_FONT_DECLARE( ui_font_InterRegular13);
LV_FONT_DECLARE( ui_font_InterSemiBold16);
LV_FONT_DECLARE( ui_font_JetBrainsMedium14);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
