// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_BG0 0
#define UI_THEME_COLOR_BG2 1
#define UI_THEME_COLOR_LN0 2
#define UI_THEME_COLOR_TX1 3
#define UI_THEME_COLOR_TX2 4
#define UI_THEME_COLOR_ACC 5
#define UI_THEME_COLOR_OKG 6
#define UI_THEME_COLOR_WRN 7
#define UI_THEME_COLOR_ERR 8

#define UI_THEME_DEFAULT 0

extern const ui_theme_variable_t _ui_theme_color_bg0[1];
extern const ui_theme_variable_t _ui_theme_alpha_bg0[1];

extern const ui_theme_variable_t _ui_theme_color_bg2[1];
extern const ui_theme_variable_t _ui_theme_alpha_bg2[1];

extern const ui_theme_variable_t _ui_theme_color_ln0[1];
extern const ui_theme_variable_t _ui_theme_alpha_ln0[1];

extern const ui_theme_variable_t _ui_theme_color_tx1[1];
extern const ui_theme_variable_t _ui_theme_alpha_tx1[1];

extern const ui_theme_variable_t _ui_theme_color_tx2[1];
extern const ui_theme_variable_t _ui_theme_alpha_tx2[1];

extern const ui_theme_variable_t _ui_theme_color_acc[1];
extern const ui_theme_variable_t _ui_theme_alpha_acc[1];

extern const ui_theme_variable_t _ui_theme_color_okg[1];
extern const ui_theme_variable_t _ui_theme_alpha_okg[1];

extern const ui_theme_variable_t _ui_theme_color_wrn[1];
extern const ui_theme_variable_t _ui_theme_alpha_wrn[1];

extern const ui_theme_variable_t _ui_theme_color_err[1];
extern const ui_theme_variable_t _ui_theme_alpha_err[1];

extern const uint32_t* ui_theme_colors[1];
extern const uint8_t* ui_theme_alphas[1];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
