// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_bg0[1] = {0x0B0F14};
const ui_theme_variable_t _ui_theme_alpha_bg0[1] = {255};

const ui_theme_variable_t _ui_theme_color_bg2[1] = {0x1C242C};
const ui_theme_variable_t _ui_theme_alpha_bg2[1] = {255};

const ui_theme_variable_t _ui_theme_color_ln0[1] = {0x2A343D};
const ui_theme_variable_t _ui_theme_alpha_ln0[1] = {255};

const ui_theme_variable_t _ui_theme_color_tx1[1] = {0xE8EDF2};
const ui_theme_variable_t _ui_theme_alpha_tx1[1] = {255};

const ui_theme_variable_t _ui_theme_color_tx2[1] = {0x8A97A3};
const ui_theme_variable_t _ui_theme_alpha_tx2[1] = {255};

const ui_theme_variable_t _ui_theme_color_acc[1] = {0x2FD3C2};
const ui_theme_variable_t _ui_theme_alpha_acc[1] = {255};

const ui_theme_variable_t _ui_theme_color_okg[1] = {0x3DDC84};
const ui_theme_variable_t _ui_theme_alpha_okg[1] = {255};

const ui_theme_variable_t _ui_theme_color_wrn[1] = {0xF5A623};
const ui_theme_variable_t _ui_theme_alpha_wrn[1] = {255};

const ui_theme_variable_t _ui_theme_color_err[1] = {0xE5484D};
const ui_theme_variable_t _ui_theme_alpha_err[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

